name: update_temperature

on:
  workflow_dispatch:

  workflow_run:
    workflows: ["daily_trigger"]
    types:
      - completed

permissions:
  contents: write

jobs:
  update-temperature:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v7
        with:
          python-version: '3.13'

      - name: clone quant-tracer
        uses: actions/checkout@v4
        with:
          repository: w3ntao/quant-tracer
          token: ${{ secrets.KEY_QUANT_TRACER_RECUR }}
          path: quant-tracer
          fetch-depth: 0
          submodules: recursive
          persist-credentials: true

      - name: prepare quant-tracer
        run: python quant-tracer/github_helper.py --prepare

      - name: trace stocks
        run: |
          pushd quant-tracer
          timeout 10m python quant_tracer.py --temperature
          mv temperature_*.png ../temperature
          popd

      - name: commit changes
        run: |
          git add temperature
          python quant-tracer/github_helper.py -commit "[ci-bot] daily temperature"
