name: update_lowvol

on:
  workflow_dispatch:

  workflow_run:
    workflows: ["daily_trigger"]
    types:
      - completed

permissions:
  contents: write

jobs:
  update-lowvol:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v7
        with:
          python-version: '3.13'

      - name: clone quant-tracer
        uses: actions/checkout@v4
        with:
          repository: w3ntao/quant-tracer
          token: ${{ secrets.KEY_QUANT_TRACER_RECUR }}
          path: quant-tracer
          fetch-depth: 0
          submodules: recursive
          persist-credentials: true

      - name: prepare quant-tracer
        run: |
          python quant-tracer/github_helper.py --prepare

      - name: trace stocks
        run: |
          pushd quant-tracer

          timeout 1h python quant_tracer.py --lowvol
          timeout 5m python quant_tracer.py --lowvol > ../lowvol/blue_stocks.txt

          timeout 30m python quant_tracer.py --lowvol_former
          timeout 5m  python quant_tracer.py --lowvol_former > ../lowvol_former/former_blue_stocks.txt

          popd

      - name: update cache
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          python quant-tracer/github_helper.py --update_cache

      - name: commit changes
        run: |
          git add lowvol lowvol_former
          python quant-tracer/github_helper.py -commit "[ci-bot] daily low vol"
