name: update_trend1000

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v7
        with:
          python-version: '3.x'

      - name: clone quant-tracer
        uses: actions/checkout@v4
        with:
          repository: w3ntao/quant-tracer
          token: ${{ secrets.KEY_QUANT_TRACER_RECUR }}
          path: quant-tracer
          fetch-depth: 0
          submodules: recursive
          persist-credentials: true

      - name: prepare quant-tracer
        run: |
          bash quant-tracer/configure.sh

      - name: trace stocks
        run: |
          pushd quant-tracer
          timeout 2h python quant_tracer.py --trend1000
          timeout 5m python quant_tracer.py --trend1000 > ../trend1000/trend1000.txt
          popd

      - name: update cache
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          python quant-tracer/github_helper.py --update_cache

      - name: commit changes
        run: |
          git add trend1000
          python quant-tracer/github_helper.py -commit "[ci-bot] daily trend1000"
