name: update_history

on:
  #push: # don't trigger workflow from push
  #  branches: ["main"]

  schedule:
    - cron: "0 17 * * 5"
    # runs at 01:00 every Saturday, Beijing time
    # 17:00 UTC Friday = 01:00 Beijing Saturday
    # cron may be delayed by GitHub Actions
  workflow_dispatch:

permissions:
  contents: write
  # so github bot could commit changes

jobs:
  update-hushen300:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6

      - name: install dependencies
        run: |
          pip install --upgrade -r requirements.txt

      - name: Set DATE variable
        env:
          TZ: Asia/Shanghai
        run: |
          echo "STOCK_DATE=$(python market_utility.py --last_stock_date)" >> $GITHUB_ENV

      - name: clone quant-tracer
        run: |
          git clone https://x-access-token:${{ secrets.KEY_QUANT_TRACER }}@github.com/w3ntao/quant-tracer.git
          pip install --upgrade -r quant-tracer/requirements.txt

      - name: trace history
        run: |
          cd quant-tracer
          timeout 1h  python quant_tracer.py --history300
          cp hushen300_*.png ../history300

          timeout 10m python quant_tracer.py --history100
          cp zhongzheng100_*.png ../history100

          cd ..

      - name: commit changes
        id: commit

        run: |
          git config user.name "Wentao Liu"
          git config user.email "wentao.liu.zero@outlook.com"

          git add history*

          git commit -m "[ci-bot] weekly update for history backtrace: ${STOCK_DATE}" || echo "No changes"
          git push -u origin main

          git checkout -B history-${STOCK_DATE}
          git push -u origin history-${STOCK_DATE}
