name: update_lowpe

on:
  #push: # don't trigger workflow from push
  #  branches: ["main"]

  workflow_dispatch:

  workflow_run:
    workflows: ["daily_trigger"]
    types:
      - completed

permissions:
  contents: write
  # so github bot could commit changes

jobs:
  update-lowpe:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash # now you can use pushd and popd

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v7
        with:
          python-version: '3.13'

      - name: clone quant-tracer
        uses: actions/checkout@v4
        with:
          repository: w3ntao/quant-tracer
          token: ${{ secrets.KEY_QUANT_TRACER_RECUR }}
          path: quant-tracer
          fetch-depth: 0 # download full history
          submodules: recursive
          persist-credentials: true

      - name: prepare quant-tracer
        run: |
          bash quant-tracer/prepare_quant_tracer.sh

      - name: trace stocks
        run: |
          pushd quant-tracer
          timeout 1h python quant_tracer.py --lowpe > "../lowpe/lowpe_stocks.txt"
          popd

      - name: commit changes
        run: |
          python quant-tracer/github_util.py \
            -add "lowpe" \
            -commit "[ci-bot] daily low PE"
